feat(route): Add /content-feed for Content Feed Service [MC-161]
mozilla-services/mozsocial-haproxy-router pull request #17
Opened 2023-09-29 21:23 UTC by mmiermans

# Goal
[MC-161](https://mozilla-hub.atlassian.net/browse/MC-161) Add a route for https://github.com/MozillaSocial/content-feed-service

2023-09-29 22:10 UTC, mmiermans commented
@bassrock Tagging you here to make sure I'm not doing anything with unexpected complications / side effects, and because I see you've made changes to this repo before. Let me know if I should've requested someone else's review.

2023-09-29 22:45 UTC, cvalaas approved these changes
I will need to create CONTENT_FEED_HOSTNAME in the deployment repo before this goes to prod, so [ping me/create a ticket] at some point before then

2023-10-02 17:31 UTC, cvalaas requested changes

2023-10-02 17:31 UTC, cvalaas commented on haproxy.cfg
> +  http-request set-header X-Forwarded-Proto https if { ssl_fc } # For Proto
```suggestion
  http-request set-header Host "${CONTENT_FEED_HOSTNAME-stage.content-feed-service.nonprod.webservices.mozgcp.net}"
  http-request set-header X-Forwarded-Proto https if { ssl_fc } # For Proto
```

2023-10-02 17:31 UTC, cvalaas commented on haproxy.cfg
> +  server content_feed "${CONTENT_FEED_HOSTNAME-stage.content-feed-service.nonprod.webservices.mozgcp.net}"
```suggestion
  server content_feed "${CONTENT_FEED_SERVICE_AND_PORT-content-feed-service.content-feed-service-stage.svc.cluster.local:8080}" maxconn "$MAXCONN_CONTENT_FEED-50}"
```

2023-10-02 17:57 UTC, merged